name: PostgreSQL service for test
on: push

jobs: 

  runs-on: ubuntu-latest

  services:
    # container postgres Label
    postgres: 
      image: postgres
      env: 
        POSTGRES_PASSWORD: 1234

      options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      ports:
       - 5432:5432
  steps:

    - name: Check out reposiotry code
      uses: actions/checkout@v4

    - name: Install all dependencies
      run: npm ci

    - name: Connect to PotgreSQL
      run: node client.js

      env: 
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432